version: '3.7'

services:
  app:
    build: .
    ports:
      - "8001:8001"
    networks:
      - app-network

  app2:
    build: .
    ports:
      - "8002:8001"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - app2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
